---
- name: setup docker on CentOS 7
  hosts: all
  tasks:
  - import_tasks: docker.yaml
    when: >
      ansible_facts['distribution'] == 'CentOS' and 
      ansible_facts['distribution_major_version'] == '7'
